/* This file was generated by github.com/ronanyeah/elm-port-gen */

export interface ElmApp {
  ports: Ports;
}

interface Ports {
  readFiles: PortOut<string[]>;
  successCb: PortOut<string>;
  errorCb: PortOut<string>;
  typesIn: PortIn<ElmFile[]>;
}

interface PortOut<T> {
  subscribe: (callback: (value: T) => void) => void;
}

interface PortIn<T> {
  send: (value: T) => void;
}

export interface Flags {
  src: string;
}

export interface ElmFile {
  path: string;
  content: string;
}
